# kube-toolkit-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-toolkit
  namespace: default
  labels:
    app: k8s-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-toolkit
  template:
    metadata:
      labels:
        app: k8s-toolkit
    spec:
      serviceAccountName: toolkit-sa
      containers:
      - name: k8s-toolkit
        image: tuo-registry/k8s-toolkit:latest
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        securityContext:
          privileged: true
        env:
          - name: ADMIN
            valueFrom:
              secretKeyRef:
                name: k8s-toolkit
                key: ADMIN
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8s-toolkit
                key: PASSWORD
        ports:
          - containerPort: 8080
            name: terminal
          - containerPort: 8081
            name: web
