apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: k8s-toolkit
  name: terminal
  namespace: default
spec:
  port:
    targetPort: terminal
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: ""
    name: k8s-toolkit
status: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: k8s-toolkit
  name: web
  namespace: default
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: ""
    name: k8s-toolkit
    weight: null
