apiVersion: v1
kind: Service
metadata:
  name: k8s-toolkit
  namespace: default
  labels:
    app: k8s-toolkit
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: terminal
    name: terminal
  - port: 8081
    protocol: TCP
    targetPort: web
    name: web
  selector:
    app: k8s-toolkit
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}